### PR TITLE
Feature/cg 2632 add facets & autocomplete to the music festival app 

### PR DESCRIPTION
**Pull request by doanthanhnguyen95**
- This is the PR to merge the story branch to main

### CODE REVIEW

**Comment by juntezhang** [comment]
I remember this repo was refactored, so we could have different samples. What we need is being able to isolate the extra search features from the basic music festival site, so 2 versions can be deployed separately.

**Review by juntezhang — COMMENTED** [review]
I remember this repo was refactored, so we could have different samples. What we need is being able to isolate the extra search features from the basic music festival site, so 2 versions can be deployed separately.

**Comment by juntezhang** [comment]
> > 
> 
> I will check with graphql squad about this and make some changes if needed.

I think easiest is to duplicate everything as a new sample/site.

**Comment by brucengdev** [comment]
There has been a restructuring of the repo recently, please rebase, and update the README file of the musicfestival-frontend-react to mention the new features demonstrated in the sample site. (facets & autocomplete)

**Review by ngoctuyennguyen-epi — APPROVED** [review]

**Pull request merged**
